export const runtime = "nodejs";
export const dynamic = "force-dynamic";
import { NextRequest } from "next/server";
import { FieldValue, adminDb } from "@/lib/firebase/admin";
import { adminFailure, adminSuccess, logAdminApiFailure } from "@/lib/firebase/admin-response";
import { isAdminSessionError, requireActiveAdminSession } from "@/lib/firebase/admin-session";
import { serializeDocument } from "@/lib/firebase/serialize-firestore";
import { normalizeDeliveryZoneName, validDeliveryFee } from "@/lib/delivery-zones";
export async function GET(){try{await requireActiveAdminSession();const s=await adminDb.collection("deliveryZones").get();return adminSuccess(s.docs.map(d=>serializeDocument(d.id,d.data()) as {sortOrder?:unknown}).sort((a,b)=>Number(a.sortOrder??0)-Number(b.sortOrder??0)))}catch(e){if(isAdminSessionError(e)){logAdminApiFailure("GET /api/admin/delivery-zones","تحميل الأحياء",e,e.status);return adminFailure(e.code,e.message,e.status)}logAdminApiFailure("GET /api/admin/delivery-zones","تحميل الأحياء",e);return adminFailure("DELIVERY_ZONES_LOAD_FAILED","تعذر تحميل الأحياء.",500)}}
export async function POST(request:NextRequest){try{const session=await requireActiveAdminSession();const body=await request.json().catch(()=>({})) as Record<string,unknown>;const name=typeof body.name==="string"?body.name.trim().replace(/\s+/g," "):"";const normalizedName=normalizeDeliveryZoneName(name);const deliveryFee=validDeliveryFee(body.deliveryFee);const sortOrder=Number(body.sortOrder);if(!name||name.length>120||deliveryFee===null||!Number.isInteger(sortOrder)||sortOrder<0)return adminFailure("INVALID_FORM_DATA","بيانات الحي غير صالحة.",400);const duplicate=await adminDb.collection("deliveryZones").where("normalizedName","==",normalizedName).limit(1).get();if(!duplicate.empty)return adminFailure("DELIVERY_ZONE_DUPLICATE","يوجد حي بنفس الاسم.",409);const ref=adminDb.collection("deliveryZones").doc();await ref.set({name,normalizedName,deliveryFee,isActive:body.isActive!==false,sortOrder,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),createdBy:session.uid});return adminSuccess({id:ref.id,message:"تمت إضافة الحي."},201)}catch(e){if(isAdminSessionError(e)){logAdminApiFailure("POST /api/admin/delivery-zones","إضافة حي",e,e.status);return adminFailure(e.code,e.message,e.status)}logAdminApiFailure("POST /api/admin/delivery-zones","إضافة حي",e);return adminFailure("ADMIN_OPERATION_FAILED","تعذر إضافة الحي.",500)}}