"use client";

import { RefreshCw } from "lucide-react";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { AdminShell } from "@/components/admin/admin-shell";
import { AdminLoadingSkeleton, AdminPageHeader } from "@/components/admin/admin-ui";
import { formatPrice } from "@/lib/format";
import { getAdminOrder, orderStatusLabel, type OrderStatusHistory } from "@/lib/firebase/services/order.service";
import type { OrderDocument } from "@/types/collections";

export default function AdminOrderDetails() {
  const id = String(useParams<{ id: string }>().id); const [order, setOrder] = useState<OrderDocument | null>(null);
  const [history, setHistory] = useState<OrderStatusHistory[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); try { const result = await getAdminOrder(id); setOrder(result.order); setHistory(result.statusHistory); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "الطلب غير موجود."); } finally { if (!silent) setLoading(false); } }, [id]);
  useEffect(() => { void Promise.resolve().then(() => load()); const interval = window.setInterval(() => void load(true), 10_000); return () => window.clearInterval(interval); }, [load]);

  return <AdminShell title="تفاصيل الطلب">{error ? <p className="rounded-xl bg-red-50 p-4 font-bold text-red-600">{error}</p> : loading || !order ? <AdminLoadingSkeleton /> : <><AdminPageHeader title={order.orderNumber} description={orderStatusLabel(order.status)} breadcrumbs={[{ label: "الطلبات", href: "/admin/orders" }, { label: order.orderNumber }]} /><div className="grid gap-5 xl:grid-cols-2"><Section title="الزبون والمطعم" rows={[["الزبون", order.customerName], ["هاتف الزبون", order.customerPhone], ["المطعم", order.restaurantName], ["هاتف المطعم", order.restaurantPhone], ["العنوان", `${order.deliveryAddress.area}، ${order.deliveryAddress.address}`]]} /><Section title="الأسعار والحالة" rows={[["المجموع الفرعي", formatPrice(order.subtotal)], ["التوصيل", formatPrice(order.deliveryFee)], ["الإجمالي", formatPrice(order.total)], ["الدفع", order.paymentStatus === "paid" ? "مدفوع" : "غير مدفوع"], ["الحالة", orderStatusLabel(order.status)]]} /><section className="rounded-2xl bg-white p-6 xl:col-span-2"><h3 className="font-black">عناصر الطلب</h3><div className="mt-4 divide-y">{order.items.map((item, index) => <div key={`${item.productId}-${index}`} className="py-4"><div className="flex justify-between font-bold"><span>{item.name} × {item.quantity}</span><span>{formatPrice(item.itemTotal)}</span></div>{item.addons.length > 0 && <p className="mt-2 text-xs text-gray-500">{item.addons.map((addon) => `${addon.name}: ${formatPrice(addon.price)}`).join("، ")}</p>}</div>)}</div></section><Section title="توقيت المراحل" rows={[["الإنشاء", date(order.createdAt)], ["القبول", date(order.acceptedAt)], ["التحضير", date(order.preparingAt)], ["الخروج للتوصيل", date(order.outForDeliveryAt)], ["التسليم", date(order.deliveredAt)]]} /><Section title="الملاحظات والأسباب" rows={[["ملاحظة الزبون", order.customerNote || "—"], ["ملاحظة المطعم", order.restaurantNote || "—"], ["سبب الرفض", order.rejectionReason || "—"], ["سبب الإلغاء", order.cancellationReason || "—"]]} /><section className="rounded-2xl bg-white p-6 xl:col-span-2"><h3 className="flex items-center gap-2 font-black"><RefreshCw className="size-5 text-primary" />سجل تغييرات الحالة</h3>{history.length ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{history.map((item) => <div key={item.id} className="rounded-xl border-r-4 border-primary bg-gray-50 p-4"><p className="font-black">{orderStatusLabel(item.status)}</p><p className="mt-1 text-xs text-gray-400">{date(item.createdAt)}</p>{item.note && <p className="mt-2 text-sm text-gray-600">{item.note}</p>}</div>)}</div> : <p className="mt-4 text-sm text-gray-400">لا توجد تغييرات مسجلة بعد.</p>}</section></div></>}</AdminShell>;
}

function Section({ title, rows }: { title: string; rows: string[][] }) { return <section className="rounded-2xl bg-white p-6"><h3 className="font-black">{title}</h3><dl className="mt-4 divide-y">{rows.map(([key, value]) => <div key={key} className="flex justify-between gap-4 py-3 text-sm"><dt className="text-gray-400">{key}</dt><dd className="font-bold">{value}</dd></div>)}</dl></section>; }
function date(value: OrderDocument["createdAt"] | null) { return value?.toDate ? new Intl.DateTimeFormat("ar-DZ-u-nu-latn", { dateStyle: "short", timeStyle: "short" }).format(value.toDate()) : "—"; }
