"use client";

import { LoaderCircle, Save } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { AdminError, AdminLoading } from "@/components/admin/admin-feedback";
import { RestaurantShell } from "@/components/restaurant-dashboard/restaurant-shell";
import { ImageUploader } from "@/components/ui/image-uploader";
import { useRestaurantAccount } from "@/features/restaurant-dashboard/restaurant-context";
import { updateRestaurantSettings } from "@/lib/firebase/services/restaurant-settings.service";
import { PushSettingsCard } from "@/features/push-notifications/push-settings-card";

const inputClass = "mt-2 h-12 w-full rounded-xl border border-gray-200 px-4 text-sm outline-none focus:border-primary focus:ring-4 focus:ring-orange-50";

export default function RestaurantSettingsPage() {
  const { restaurant, loading, refresh } = useRestaurantAccount();
  const [logo, setLogo] = useState({ url: "", publicId: "" }); const [cover, setCover] = useState({ url: "", publicId: "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { if (restaurant) void Promise.resolve().then(() => { setLogo({ url: restaurant.logoUrl, publicId: restaurant.logoPublicId }); setCover({ url: restaurant.coverUrl, publicId: restaurant.coverPublicId }); }); }, [restaurant]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!restaurant || saving) return; setSaving(true); setError(""); setSuccess(""); const form = new FormData(event.currentTarget);
    try { await updateRestaurantSettings({ description: String(form.get("description") ?? "").trim(), phone: String(form.get("phone") ?? "").trim(), address: String(form.get("address") ?? "").trim(), logoUrl: logo.url, logoPublicId: logo.publicId, coverUrl: cover.url, coverPublicId: cover.publicId, deliveryTime: String(form.get("deliveryTime") ?? "").trim(), deliveryFee: Number(form.get("deliveryFee")), minimumOrder: Number(form.get("minimumOrder")), isOpen: form.get("isOpen") === "on", workingHours: String(form.get("workingHours") ?? "").trim() }); await refresh(); setSuccess("تم حفظ إعدادات المطعم بنجاح."); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر حفظ الإعدادات."); } finally { setSaving(false); }
  }
  return <RestaurantShell title="إعدادات المطعم">{loading || !restaurant ? <AdminLoading /> : <form onSubmit={submit} className="space-y-6">{error && <AdminError message={error} />}{success && <div className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{success}</div>}<section className="grid gap-5 rounded-3xl bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-7"><label className="text-sm font-bold">اسم المطعم<input value={restaurant.name} readOnly className={`${inputClass} cursor-not-allowed bg-gray-50 text-gray-500`} /></label><label className="text-sm font-bold">رقم الهاتف<input name="phone" defaultValue={restaurant.phone} className={inputClass} required /></label><label className="text-sm font-bold sm:col-span-2">الوصف<textarea name="description" defaultValue={restaurant.description} rows={3} className={`${inputClass} h-auto py-3`} required /></label><label className="text-sm font-bold sm:col-span-2">العنوان<input name="address" defaultValue={restaurant.address} className={inputClass} required /></label><label className="text-sm font-bold">مدة التوصيل<input name="deliveryTime" defaultValue={restaurant.deliveryTime} placeholder="مثال: من 30 إلى 45 دقيقة" className={inputClass} required /></label><label className="text-sm font-bold">ساعات العمل<input name="workingHours" defaultValue={restaurant.workingHours} placeholder="مثال: من 11 صباحاً إلى 11 مساءً" className={inputClass} required /></label><label className="text-sm font-bold">سعر التوصيل<input name="deliveryFee" type="number" min="0" defaultValue={restaurant.deliveryFee} className={inputClass} required /></label><label className="text-sm font-bold">الحد الأدنى للطلب<input name="minimumOrder" type="number" min="0" defaultValue={restaurant.minimumOrder} className={inputClass} required /></label><label className="flex items-center gap-2 text-sm font-bold sm:col-span-2"><input name="isOpen" type="checkbox" defaultChecked={restaurant.isOpen} className="size-4 accent-primary" />المطعم مفتوح لاستقبال الزبائن</label></section><section className="grid gap-6 rounded-3xl bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-7"><ImageUploader label="شعار المطعم" folder="jibli/restaurants/logos" value={logo.url} onUploaded={({ url, publicId }) => setLogo({ url, publicId })} /><ImageUploader label="غلاف المطعم" folder="jibli/restaurants/covers" value={cover.url} onUploaded={({ url, publicId }) => setCover({ url, publicId })} /></section><PushSettingsCard /><button type="submit" disabled={saving} className="flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-primary font-black text-white disabled:opacity-60 sm:w-56">{saving ? <LoaderCircle className="size-5 animate-spin" /> : <Save className="size-5" />}{saving ? "جاري الحفظ..." : "حفظ الإعدادات"}</button></form>}</RestaurantShell>;
}
