"use client";
import { AlertTriangle, ChevronLeft, ChevronRight, Search, X } from "lucide-react"; import Link from "next/link"; import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from "react";

export function AdminPageHeader({ title, description, action, breadcrumbs = [] }: { title: string; description?: string; action?: ReactNode; breadcrumbs?: { label: string; href?: string }[] }) { return <div className="mb-6"><div className="mb-3 flex items-center gap-2 text-xs text-gray-400"><Link href="/admin">الإدارة</Link>{breadcrumbs.map((item) => <span key={item.label} className="flex items-center gap-2"><ChevronLeft className="size-3" />{item.href ? <Link href={item.href}>{item.label}</Link> : item.label}</span>)}</div><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-black">{title}</h2>{description && <p className="mt-1 text-sm text-gray-500">{description}</p>}</div>{action}</div></div>; }
export function AdminStatCard({ label, value, icon: Icon, note }: { label: string; value: string | number; icon: React.ComponentType<{ className?: string }>; note?: string }) { return <article className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-gray-500">{label}</p><p className="mt-3 text-3xl font-black">{typeof value === "number" ? new Intl.NumberFormat("ar-DZ-u-nu-latn").format(value) : value}</p></div><span className="grid size-11 place-items-center rounded-xl bg-orange-50 text-primary"><Icon className="size-5" /></span></div>{note && <p className="mt-3 text-xs text-gray-400">{note}</p>}</article>; }
export function AdminSearchInput({ value, onChange, placeholder = "ابحث..." }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="relative block min-w-64"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-gray-400" /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="h-11 w-full rounded-xl border border-gray-200 bg-white pr-10 pl-3 text-sm outline-none focus:border-primary" /></label>; }
export function AdminFilterBar({ children }: { children: ReactNode }) { return <div className="mb-4 flex flex-wrap items-center gap-3 rounded-2xl border border-gray-100 bg-white p-4">{children}</div>; }
export function AdminDataTable({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-gray-100 bg-white"><table className="min-w-[760px] w-full text-right text-sm"><thead className="sticky top-17 bg-gray-50 text-xs text-gray-500"><tr>{headers.map((header) => <th key={header} className="p-4">{header}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{children}</tbody></table></div>; }
export function StatusBadge({ active, activeLabel = "نشط", inactiveLabel = "موقوف" }: { active: boolean; activeLabel?: string; inactiveLabel?: string }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-black ${active ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-600"}`}>{active ? activeLabel : inactiveLabel}</span>; }
export const RestaurantStatusBadge = ({ isOpen }: { isOpen: boolean }) => <StatusBadge active={isOpen} activeLabel="مفتوح" inactiveLabel="مغلق" />;
export function UserRoleBadge({ role }: { role: string }) { const labels: Record<string, string> = { admin: "إدارة", restaurant: "مطعم", customer: "زبون" }; return <span className="rounded-full bg-orange-50 px-2.5 py-1 text-[11px] font-black text-primary">{labels[role] ?? role}</span>; }
export function AdminPagination({ page, pages, onChange }: { page: number; pages: number; onChange: (page: number) => void }) { if (pages <= 1) return null; return <div className="mt-5 flex items-center justify-center gap-3"><button disabled={page <= 1} onClick={() => onChange(page - 1)} className="grid size-10 place-items-center rounded-xl border disabled:opacity-40"><ChevronRight className="size-4" /></button><span className="text-sm font-bold">صفحة {page} من {pages}</span><button disabled={page >= pages} onClick={() => onChange(page + 1)} className="grid size-10 place-items-center rounded-xl border disabled:opacity-40"><ChevronLeft className="size-4" /></button></div>; }
export function AdminEmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-gray-200 bg-white p-12 text-center"><p className="font-black">{title}</p><p className="mt-2 text-sm text-gray-500">{description}</p></div>; }
export function AdminLoadingSkeleton() { return <div className="space-y-3 animate-pulse">{[1,2,3,4].map((item) => <div key={item} className="h-16 rounded-xl bg-gray-100" />)}</div>; }
export function AdminFormSection({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><div className="mb-5"><h3 className="font-black">{title}</h3>{description && <p className="mt-1 text-xs text-gray-400">{description}</p>}</div>{children}</section>; }

type Toast = { id: number; message: string; type: "success" | "error" }; const ToastContext = createContext<{ show: (message: string, type?: Toast["type"]) => void } | null>(null);
export function ToastProvider({ children }: { children: ReactNode }) { const [toasts, setToasts] = useState<Toast[]>([]); const timers = useRef<Set<number>>(new Set()); useEffect(() => () => { timers.current.forEach((timer) => window.clearTimeout(timer)); timers.current.clear(); }, []); const dismiss = useCallback((id: number) => setToasts((items) => items.filter((item) => item.id !== id)), []); const show = useCallback((message: string, type: Toast["type"] = "success") => { const id = Date.now(); setToasts((items) => [...items, { id, message, type }]); const timer = window.setTimeout(() => { dismiss(id); timers.current.delete(timer); }, 3500); timers.current.add(timer); }, [dismiss]); return <ToastContext.Provider value={{ show }}>{children}<div className="fixed bottom-5 left-5 z-[100] space-y-2">{toasts.map((toast) => <div key={toast.id} role="status" className={`flex min-w-72 items-center justify-between rounded-xl px-4 py-3 text-sm font-bold text-white shadow-xl ${toast.type === "success" ? "bg-emerald-600" : "bg-red-600"}`}><span>{toast.message}</span><button type="button" aria-label="إغلاق التنبيه" onClick={() => dismiss(toast.id)}><X className="size-4" /></button></div>)}</div></ToastContext.Provider>; }
export function useAdminToast() { const value = useContext(ToastContext); if (!value) throw new Error("مزود التنبيهات غير متاح."); return value; }
export function AdminConfirmDialog({ open, title, message, busy, onConfirm, onClose }: { open: boolean; title: string; message: string; busy?: boolean; onConfirm: () => void; onClose: () => void }) { if (!open) return null; return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><AlertTriangle className="size-9 text-amber-500" /><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{message}</p><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} disabled={busy} className="h-11 rounded-xl border px-5 font-bold">إلغاء</button><button onClick={onConfirm} disabled={busy} className="h-11 rounded-xl bg-red-600 px-5 font-bold text-white disabled:opacity-50">{busy ? "جاري التنفيذ..." : "تأكيد"}</button></div></div></div>; }

