"use client";

import { Bell, ChevronLeft, ChevronRight, CircleHelp, FileBarChart, FolderTree, Gift, House, LogOut, Menu, MessageSquareWarning, Search, Settings, ShieldCheck, ShoppingBag, Store, MapPinned, Users, UtensilsCrossed, X } from "lucide-react";
import Link from "next/link"; import { usePathname, useRouter } from "next/navigation"; import { useState, type ReactNode } from "react"; import { useAuth } from "@/features/auth/auth-context";

const links = [
  { href: "/admin", label: "الرئيسية", icon: House, exact: true }, { href: "/admin/restaurants", label: "المطاعم", icon: Store }, { href: "/admin/delivery-zones", label: "أحياء التوصيل", icon: MapPinned }, { href: "/admin/categories", label: "التصنيفات", icon: FolderTree }, { href: "/admin/products", label: "الأكلات", icon: UtensilsCrossed }, { href: "/admin/orders", label: "الطلبات", icon: ShoppingBag }, { href: "/admin/customers", label: "الزبائن", icon: Users }, { href: "/admin/users?role=restaurant", label: "مستخدمو المطاعم", icon: CircleHelp }, { href: "/admin/offers", label: "العروض", icon: Gift }, { href: "/admin/complaints", label: "الشكاوى", icon: MessageSquareWarning }, { href: "/admin/notifications", label: "الإشعارات", icon: Bell }, { href: "/admin/reports", label: "التقارير", icon: FileBarChart }, { href: "/admin/settings", label: "الإعدادات", icon: Settings }, { href: "/admin/system-check", label: "فحص النظام", icon: ShieldCheck },
];
export function AdminShell({ children, title }: { children: ReactNode; title: string }) {
  const pathname = usePathname(); const router = useRouter(); const { profile, signOut } = useAuth(); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const [accountOpen, setAccountOpen] = useState(false);
  async function leave() { await signOut(); router.replace("/login"); }
  const navigation = <><div className="flex h-17 items-center justify-between border-b border-white/10 px-4"><Link href="/admin" className="overflow-hidden text-2xl font-black text-primary">{collapsed ? "ج" : "جيبلي"}</Link><button aria-label="إغلاق القائمة" onClick={() => setMobileOpen(false)} className="md:hidden"><X className="size-5" /></button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{links.map(({ href, label, icon: Icon, exact }) => { const cleanHref = href.split("?")[0]; const active = exact ? pathname === cleanHref : pathname.startsWith(cleanHref); return <Link key={href} href={href} title={collapsed ? label : undefined} onClick={() => setMobileOpen(false)} className={`flex h-11 items-center gap-3 rounded-xl px-3 text-sm font-bold transition ${active ? "bg-primary text-white" : "text-white/65 hover:bg-white/5 hover:text-white"}`}><Icon className="size-5 shrink-0" />{!collapsed && <span className="truncate">{label}</span>}</Link>; })}</nav><button onClick={leave} className="m-3 flex h-11 items-center justify-center gap-2 rounded-xl bg-white/10 text-sm font-bold text-white"><LogOut className="size-5" />{!collapsed && "تسجيل الخروج"}</button></>;
  return <div className={`min-h-dvh overflow-x-hidden bg-[#f7f8fa] md:grid ${collapsed ? "md:grid-cols-[76px_minmax(0,1fr)]" : "md:grid-cols-[260px_minmax(0,1fr)]"}`}><aside className="sticky top-0 hidden h-dvh flex-col bg-gray-950 text-white md:flex">{navigation}<button onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? "توسيع القائمة" : "طي القائمة"} className="absolute -left-3 top-20 grid size-7 place-items-center rounded-full border border-gray-200 bg-white text-gray-700 shadow">{collapsed ? <ChevronLeft className="size-4" /> : <ChevronRight className="size-4" />}</button></aside>{mobileOpen && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="إغلاق القائمة" onClick={() => setMobileOpen(false)} className="absolute inset-0 bg-black/50" /><aside className="relative flex h-full w-72 flex-col bg-gray-950 text-white">{navigation}</aside></div>}<div className="min-w-0"><header className="sticky top-0 z-40 flex h-17 items-center gap-4 border-b border-gray-100 bg-white/95 px-4 backdrop-blur lg:px-7"><button onClick={() => setMobileOpen(true)} aria-label="فتح القائمة" className="grid size-10 place-items-center rounded-xl bg-gray-100 md:hidden"><Menu className="size-5" /></button><h1 className="shrink-0 text-lg font-black">{title}</h1><label className="relative mr-auto hidden w-full max-w-md lg:block"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-gray-400" /><input placeholder="بحث عام في لوحة الإدارة" className="h-10 w-full rounded-xl bg-gray-100 pr-10 pl-3 text-sm outline-none focus:ring-2 focus:ring-orange-100" /></label><button aria-label="الإشعارات" className="relative grid size-10 place-items-center rounded-xl bg-gray-100"><Bell className="size-5" /><span className="absolute left-2 top-2 size-2 rounded-full bg-primary" /></button><div className="relative"><button onClick={() => setAccountOpen((value) => !value)} className="flex items-center gap-3 rounded-xl p-1.5 hover:bg-gray-50"><span className="grid size-9 place-items-center rounded-xl bg-gray-950 font-black text-white">{profile?.firstName?.slice(0,1) || "م"}</span><span className="hidden text-right sm:block"><span className="block text-sm font-black">{profile?.fullName || "مدير جيبلي"}</span><span className="block text-[10px] text-gray-400">حساب الإدارة</span></span></button>{accountOpen && <div className="absolute left-0 top-12 w-48 rounded-xl border border-gray-100 bg-white p-2 shadow-xl"><Link href="/profile" className="block rounded-lg px-3 py-2 text-sm font-bold hover:bg-gray-50">بيانات الحساب</Link><button onClick={leave} className="w-full rounded-lg px-3 py-2 text-right text-sm font-bold text-red-600 hover:bg-red-50">تسجيل الخروج</button></div>}</div></header><main className="min-h-[calc(100dvh-68px)] min-w-0 p-4 lg:p-7">{children}</main></div></div>;
}
