"use client";

import { BellOff, BellRing, LoaderCircle, Send } from "lucide-react";
import { useEffect, useState } from "react";
import { deleteCurrentPushToken, isPushSupported, pushApiRequest, registerPushNotifications } from "@/lib/firebase/messaging";
import { usePushNotifications } from "./push-provider";

type State = "loading" | "enabled" | "disabled" | "denied" | "unsupported" | "unconfigured";
const configured = Boolean(process.env.NEXT_PUBLIC_FIREBASE_VAPID_KEY?.trim());

export function PushSettingsCard() {
  const { primeAudio } = usePushNotifications(); const [state, setState] = useState<State>("loading"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.resolve().then(() => { if (!configured) setState("unconfigured"); else if (!isPushSupported()) setState("unsupported"); else if (Notification.permission === "denied") setState("denied"); else setState(localStorage.getItem("jibli_push_enabled") === "true" && Notification.permission === "granted" ? "enabled" : "disabled"); }); }, []);
  async function enable() { if (busy) return; setBusy(true); setMessage(""); primeAudio(); try { const result = await registerPushNotifications(); if (result.permission === "denied") { setState("denied"); setMessage("تم رفض إذن الإشعارات. يمكنك تفعيله لاحقاً من إعدادات المتصفح."); } else if (result.permission === "granted") { setState("enabled"); setMessage("تم تفعيل إشعارات الطلبات."); } } catch { setMessage("تعذر تفعيل الإشعارات. تحقق من إعداد Firebase."); } finally { setBusy(false); } }
  async function disable() { if (busy) return; setBusy(true); setMessage(""); try { await deleteCurrentPushToken(); setState("disabled"); setMessage("تم إيقاف إشعارات الطلبات على هذا الجهاز."); } catch { setMessage("تعذر إيقاف الإعارات."); } finally { setBusy(false); } }
  async function test() { if (busy) return; setBusy(true); setMessage(""); try { const response = await pushApiRequest("/api/push/test", { method: "POST" }); setMessage(response.ok ? "تم إرسال إشعار الاختبار." : "تعذر إرسال الاختبار."); } catch { setMessage("تعذر إرسال الاختبار."); } finally { setBusy(false); } }
  const iphone = typeof navigator !== "undefined" && /iPhone|iPad|iPod/.test(navigator.userAgent) && !window.matchMedia("(display-mode: standalone)").matches;
  const labels: Record<State, string> = { loading: "جاري التحقق...", enabled: "مفعلة", disabled: "غير مفعلة", denied: "مرفوضة من المتصفح", unsupported: "المتصفح غير مدعوم", unconfigured: "Push Notifications غير مهيأة" };
  return <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-primary-soft text-primary">{state === "enabled" ? <BellRing className="size-5" /> : <BellOff className="size-5" />}</span><div className="min-w-0 flex-1"><h2 className="font-black">إشعارات الطلبات</h2><p className="mt-1 text-xs text-gray-500">{labels[state]}</p></div></div>{iphone && <p className="mt-4 rounded-2xl bg-amber-50 p-3 text-xs leading-6 text-amber-800">ثبّت جيبلي على الشاشة الرئيسية، ثم افتحه واضغط تفعيل الإشعارات.</p>}{message && <p className="mt-4 text-xs font-bold leading-6 text-gray-600">{message}</p>}<div className="mt-4 flex flex-wrap gap-2">{state === "enabled" ? <><button type="button" disabled={busy} onClick={disable} className="h-10 rounded-xl bg-gray-100 px-4 text-xs font-black">إيقاف الإشعارات</button><button type="button" disabled={busy} onClick={test} className="flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-black text-white"><Send className="size-4" />اختبار الإشعار</button></> : !["unsupported", "unconfigured", "denied", "loading"].includes(state) && <button type="button" disabled={busy} onClick={enable} className="flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-black text-white">{busy && <LoaderCircle className="size-4 animate-spin" />}تفعيل الإشعارات</button>}</div></section>;
}