"use client";
import { BellRing, LoaderCircle, X } from "lucide-react";
import { useEffect,useState } from "react";
import { useAuth } from "@/features/auth/auth-context";
import { isPushSupported,registerPushNotifications } from "@/lib/firebase/messaging";
import { usePushNotifications } from "./push-provider";
const DISMISS_KEY="pushPromptDismissedAt";
const WEEK=7*24*60*60*1000;
export function PushPermissionPrompt(){
 const {user,role,status}=useAuth();const {primeAudio}=usePushNotifications();const [visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!user||role!=="customer"||status!=="active"||!canPrompt())return;const dismissed=Number(localStorage.getItem(DISMISS_KEY)||0);if(dismissed&&Date.now()-dismissed<WEEK)return;const timer=window.setTimeout(()=>setVisible(true),1800);return()=>window.clearTimeout(timer)},[role,status,user]);
 function dismiss(){localStorage.setItem(DISMISS_KEY,String(Date.now()));setVisible(false)}
 async function enable(){if(busy)return;setBusy(true);setMessage("");primeAudio();try{const result=await registerPushNotifications();if(result.permission==="granted"){localStorage.removeItem(DISMISS_KEY);setMessage("تم تفعيل إشعارات الطلبات.");window.dispatchEvent(new Event("jibli:push-setting-changed"));window.setTimeout(()=>setVisible(false),1400)}else if(result.permission==="denied"){localStorage.setItem(DISMISS_KEY,String(Date.now()));setMessage("الإشعارات مرفوضة من إعدادات المتصفح.")}else setMessage("الإشعارات غير مدعومة على هذا الجهاز.")}catch(caught){setMessage(caught instanceof Error&&caught.message==="PUSH_NOT_CONFIGURED"?"خدمة الإشعارات غير مهيأة حالياً.":"تعذر تفعيل الإشعارات. حاول من إعدادات الحساب.")}finally{setBusy(false)}}
 if(!visible)return null;
 return <div className="fixed inset-0 z-[120] flex items-end bg-black/45 p-0 sm:items-center sm:justify-center sm:p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="push-prompt-title" className="w-full rounded-t-[24px] bg-white p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] shadow-2xl sm:max-w-md sm:rounded-3xl"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-orange-50 text-primary"><BellRing className="size-6"/></span><button type="button" onClick={dismiss} aria-label="إغلاق" className="grid size-11 place-items-center rounded-xl bg-gray-100"><X className="size-5"/></button></div><h2 id="push-prompt-title" className="mt-4 text-xl font-black">خليك على اطلاع بطلبك 🔔</h2><p className="mt-2 text-sm leading-7 text-gray-500">فعّل الإشعارات كي تكون مطلع على طلبك</p>{message&&<p role="status" className="mt-3 rounded-xl bg-orange-50 p-3 text-sm font-bold text-gray-700">{message}</p>}<div className="mt-5 grid gap-2"><button type="button" onClick={()=>void enable()} disabled={busy} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-primary font-black text-white disabled:opacity-60">{busy&&<LoaderCircle className="size-5 animate-spin"/>}{busy?"جاري التفعيل...":"تفعيل الإشعارات"}</button><button type="button" onClick={dismiss} className="min-h-12 rounded-2xl bg-gray-100 font-black">لاحقاً</button></div></section></div>
}
function canPrompt(){if(!isPushSupported()||Notification.permission!=="default"||localStorage.getItem("jibli_push_enabled")==="true"||!process.env.NEXT_PUBLIC_FIREBASE_VAPID_KEY?.trim())return false;const ua=navigator.userAgent;const ios=/iPad|iPhone|iPod/.test(ua);const standalone=window.matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone===true;return !ios||standalone}
