export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { Timestamp } from "@/lib/firebase/admin";
import { adminDb } from "@/lib/firebase/admin";
import { adminFailure,adminSuccess,logAdminApiFailure } from "@/lib/firebase/admin-response";
import { isAdminSessionError,requireActiveAdminSession } from "@/lib/firebase/admin-session";
const millis=(value:unknown)=>value instanceof Timestamp?value.toMillis():value instanceof Date?value.getTime():typeof value==="string"?Date.parse(value)||0:0;
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;
export async function GET(){try{await requireActiveAdminSession();const db=adminDb;const[orders,restaurants,users,products]=await Promise.all([db.collection("orders").orderBy("createdAt","desc").limit(5000).get(),db.collection("restaurants").get(),db.collection("users").get(),db.collection("products").get()]);const restaurantNames=new Map(restaurants.docs.map(doc=>[doc.id,String(doc.data().name??"")]));const productNames=new Map(products.docs.map(doc=>[doc.id,String(doc.data().name??"")]));const byDay=new Map<string,{orders:number;sales:number}>();const byRestaurant=new Map<string,{orders:number;sales:number}>();const byProduct=new Map<string,{quantity:number;total:number}>();let rejected=0,cancelled=0;for(const document of orders.docs){const order=document.data();const date=new Date(millis(order.createdAt));const day=Number.isNaN(date.getTime())?"غير مؤرخ":date.toISOString().slice(0,10);const daily=byDay.get(day)??{orders:0,sales:0};daily.orders++;if(order.status==="delivered")daily.sales+=number(order.total);byDay.set(day,daily);const restaurantId=String(order.restaurantId??"");const restaurant=byRestaurant.get(restaurantId)??{orders:0,sales:0};restaurant.orders++;if(order.status==="delivered")restaurant.sales+=number(order.total);byRestaurant.set(restaurantId,restaurant);if(order.status==="rejected")rejected++;if(order.status==="cancelled")cancelled++;if(Array.isArray(order.items))for(const raw of order.items){const item=raw as Record<string,unknown>;const id=String(item.productId??"");const row=byProduct.get(id)??{quantity:0,total:0};row.quantity+=number(item.quantity);row.total+=number(item.itemTotal);byProduct.set(id,row)}}const since=Date.now()-30*86400000;return adminSuccess({summary:{orders:orders.size,sales:[...byDay.values()].reduce((sum,row)=>sum+row.sales,0),rejected,cancelled,newCustomers:users.docs.filter(doc=>doc.data().role==="customer"&&millis(doc.data().createdAt)>=since).length,newRestaurants:restaurants.docs.filter(doc=>millis(doc.data().createdAt)>=since).length},daily:[...byDay.entries()].sort(([a],[b])=>b.localeCompare(a)).slice(0,30).map(([date,value])=>({date,...value})),restaurants:[...byRestaurant.entries()].map(([id,value])=>({id,name:restaurantNames.get(id)||"مطعم غير معروف",...value})).sort((a,b)=>b.orders-a.orders).slice(0,20),products:[...byProduct.entries()].map(([id,value])=>({id,name:productNames.get(id)||"أكلة غير موجودة",...value})).sort((a,b)=>b.quantity-a.quantity).slice(0,20)})}catch(error){logAdminApiFailure("GET /api/admin/reports","إنشاء التقارير",error);if(isAdminSessionError(error))return adminFailure(error.code,error.message,error.status);return adminFailure("ADMIN_OPERATION_FAILED","تعذر تحميل التقارير.",500)}}
