"use client";
import { Ban,ShoppingBag,Store,Users,UtensilsCrossed,WalletCards } from "lucide-react";
import { useCallback,useEffect,useState } from "react";
import { AdminShell } from "@/components/admin/admin-shell";
import { AdminLoadingSkeleton,AdminPageHeader,AdminStatCard } from "@/components/admin/admin-ui";
import { formatPrice } from "@/lib/format";
import { getAdminReports,type AdminReportData } from "@/lib/firebase/services/admin-report.service";
export default function ReportsPage(){const[data,setData]=useState<AdminReportData|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{setError("");try{setData(await getAdminReports())}catch(error){setError(error instanceof Error?error.message:"تعذر تحميل التقارير.")}},[]);useEffect(()=>{void Promise.resolve().then(load)},[load]);return <AdminShell title="التقارير"><AdminPageHeader title="التقارير" description="تقارير فعلية محسوبة من الطلبات والمستخدمين والمطاعم" breadcrumbs={[{label:"التقارير"}]}/>{error&&<div className="mb-4 flex justify-between rounded-xl bg-red-50 p-4 text-sm font-bold text-red-600"><span>{error}</span><button onClick={()=>void load()}>إعادة المحاولة</button></div>}{!data&&!error?<AdminLoadingSkeleton/>:data?<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><AdminStatCard label="كل الطلبات" value={data.summary.orders} icon={ShoppingBag}/><AdminStatCard label="مبيعات الطلبات المسلمة" value={formatPrice(data.summary.sales)} icon={WalletCards}/><AdminStatCard label="المرفوضة والملغاة" value={data.summary.rejected+data.summary.cancelled} icon={Ban}/><AdminStatCard label="زبائن جدد خلال 30 يوماً" value={data.summary.newCustomers} icon={Users}/><AdminStatCard label="مطاعم جديدة خلال 30 يوماً" value={data.summary.newRestaurants} icon={Store}/><AdminStatCard label="الأكلات المطلوبة" value={data.products.reduce((sum,row)=>sum+row.quantity,0)} icon={UtensilsCrossed}/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Table title="الطلبات والمبيعات حسب اليوم" headers={["اليوم","الطلبات","المبيعات"]} rows={data.daily.map(row=>[row.date,String(row.orders),formatPrice(row.sales)])}/><Table title="أكثر المطاعم طلباً" headers={["المطعم","الطلبات","المبيعات"]} rows={data.restaurants.map(row=>[row.name,String(row.orders),formatPrice(row.sales)])}/><Table title="أكثر الأكلات طلباً" headers={["الأكلة","الكمية","القيمة"]} rows={data.products.map(row=>[row.name,String(row.quantity),formatPrice(row.total)])}/><Table title="الطلبات غير المكتملة" headers={["الحالة","العدد"]} rows={[["مرفوضة",String(data.summary.rejected)],["ملغاة",String(data.summary.cancelled)]]}/></div></>:null}</AdminShell>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <section className="overflow-hidden rounded-2xl border bg-white"><h2 className="border-b p-5 font-black">{title}</h2>{rows.length?<div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead className="bg-gray-50"><tr>{headers.map(item=><th key={item} className="p-3 text-xs text-gray-500">{item}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,i)=><td key={`${i}-${cell}`} className="p-3">{cell}</td>)}</tr>)}</tbody></table></div>:<p className="p-5 text-sm text-gray-400">لا توجد بيانات حالياً.</p>}</section>}
