import { Timestamp } from "firebase-admin/firestore";
import { getAdminDb } from "@/lib/firebase/admin";
import { adminFailure, adminSuccess, logAdminApiFailure } from "@/lib/firebase/admin-response";
import { isAdminSessionError, requireActiveAdminSession } from "@/lib/firebase/admin-session";
import { serializeFirestoreData } from "@/lib/firebase/serialize-firestore";

const millis=(value:unknown)=>value instanceof Timestamp?value.toMillis():value instanceof Date?value.getTime():typeof value==="string"?Date.parse(value)||0:0;
const amount=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;
export async function GET(){try{await requireActiveAdminSession();const db=getAdminDb();const [users,orders]=await Promise.all([db.collection("users").where("role","==","customer").get(),db.collection("orders").orderBy("createdAt","desc").limit(5000).get()]);const grouped=new Map<string,Record<string,unknown>[]>();for(const document of orders.docs){const value=document.data();const id=typeof value.customerId==="string"?value.customerId:"";if(id)grouped.set(id,[...(grouped.get(id)??[]),value])}const customers=users.docs.map(document=>{const value=document.data();const customerOrders=grouped.get(document.id)??[];const delivered=customerOrders.filter(order=>order.status==="delivered");return{uid:document.id,firstName:value.firstName??"",lastName:value.lastName??"",fullName:value.fullName??"",email:value.email??"",phone:value.phone??"",status:value.status??"active",role:"customer",createdAt:value.createdAt??null,updatedAt:value.updatedAt??null,lastLoginAt:value.lastLoginAt??null,ordersCount:customerOrders.length,totalSpent:delivered.reduce((sum,order)=>sum+amount(order.total),0),lastOrderAt:customerOrders[0]?.createdAt??null}}).sort((a,b)=>millis(b.createdAt)-millis(a.createdAt)).map(serializeFirestoreData);return adminSuccess({customers,total:customers.length})}catch(error){logAdminApiFailure("GET /api/admin/customers","تحميل الزبائن وإحصاء طلباتهم",error);if(isAdminSessionError(error))return adminFailure(error.code,error.message,error.status);return adminFailure("CUSTOMERS_LOAD_FAILED","تعذر تحميل الزبائن.",500)}}
