"use client";
import { LogOut, Mail, MessageSquareWarning, Phone, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { PageContainer } from "@/components/layout/page-container";
import { AuthLoading } from "@/features/auth/auth-loading";
import { useAuth } from "@/features/auth/auth-context";
import { roleLabels, statusLabels } from "@/types/auth"; import { PushSettingsCard } from "@/features/push-notifications/push-settings-card";
export default function ProfilePage(){const router=useRouter();const{profile,loading,signOut}=useAuth();const[signingOut,setSigningOut]=useState(false);if(loading||!profile)return <AuthLoading/>;async function handleSignOut(){if(signingOut)return;setSigningOut(true);await signOut();router.replace("/login")}const details=[{label:"البريد الإلكتروني",value:profile.email,icon:Mail},{label:"رقم الهاتف",value:profile.phone,icon:Phone},{label:"نوع الحساب",value:roleLabels[profile.role],icon:UserRound},{label:"حالة الحساب",value:statusLabels[profile.status],icon:ShieldCheck}];return <AppShell title="الحساب"><PageContainer className="max-w-2xl py-7"><section className="flex items-center gap-4 rounded-3xl bg-gray-950 p-5 text-white shadow-sm"><span className="grid size-18 place-items-center rounded-full bg-primary"><UserRound className="size-8"/></span><div className="min-w-0"><p className="text-sm text-white/55">مرحباً بك</p><h1 className="mt-1 truncate text-xl font-black">{profile.fullName}</h1></div></section><section className="mt-5 overflow-hidden rounded-3xl bg-white px-5 shadow-sm">{details.map(({label,value,icon:Icon},index)=><div key={label} className={`flex items-center gap-3 py-4 ${index<details.length-1?"border-b border-gray-100":""}`}><span className="grid size-11 place-items-center rounded-2xl bg-orange-50 text-primary"><Icon className="size-5"/></span><span className="min-w-0 flex-1"><span className="block text-xs text-gray-400">{label}</span><span className="mt-1 block truncate text-sm font-black">{value}</span></span></div>)}</section><div className="mt-5"><PushSettingsCard /></div><Link href="/complaints" className="mt-5 flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-white font-black text-gray-800 shadow-sm"><MessageSquareWarning className="size-5 text-primary"/>الشكاوى والدعم</Link><button type="button" disabled={signingOut} onClick={handleSignOut} className="mt-5 flex h-13 w-full items-center justify-center gap-2 rounded-2xl border border-red-100 bg-red-50 font-black text-red-600 disabled:opacity-60"><LogOut className="size-5"/>{signingOut?"جاري تسجيل الخروج...":"تسجيل الخروج"}</button></PageContainer></AppShell>}