"use client";

import { Pencil, Plus, Search, Trash2, UtensilsCrossed } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AdminError, AdminLoading } from "@/components/admin/admin-feedback";
import { RestaurantShell } from "@/components/restaurant-dashboard/restaurant-shell";
import { EmptyState } from "@/components/ui/empty-state";
import { useRestaurantAccount } from "@/features/restaurant-dashboard/restaurant-context";
import { getRestaurantCategories, type RestaurantCategory } from "@/lib/firebase/services/restaurant-category.service";
import { deleteRestaurantProduct, getRestaurantProducts, updateRestaurantProduct } from "@/lib/firebase/services/restaurant-product.service";
import { formatPrice } from "@/lib/format";
import type { ProductDocument } from "@/types/collections";

export default function RestaurantProductsPage() {
  const { restaurant } = useRestaurantAccount(); const [items, setItems] = useState<ProductDocument[]>([]); const [categories, setCategories] = useState<RestaurantCategory[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [availability, setAvailability] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const [products, categoryItems] = await Promise.all([getRestaurantProducts(), getRestaurantCategories()]); setItems(products); setCategories(categoryItems); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر تحميل الأكلات."); } finally { setLoading(false); } }, []);
  useEffect(() => { let active = true; Promise.all([getRestaurantProducts(), getRestaurantCategories()]).then(([products, categoryItems]) => { if (active) { setItems(products); setCategories(categoryItems); setError(""); setLoading(false); } }).catch((caught) => { if (active) { setError(caught instanceof Error ? caught.message : "تعذر تحميل الأكلات."); setLoading(false); } }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => items.filter((item) => item.name.includes(search.trim()) && (!category || item.categoryId === category) && (!availability || String(item.isAvailable) === availability)), [availability, category, items, search]);
  async function remove(id: string) { if (busy || !window.confirm("هل تريد حذف هذه الأكلة نهائياً؟")) return; setBusy(id); try { await deleteRestaurantProduct(id); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر حذف الأكلة."); } finally { setBusy(""); } }
  async function toggle(item: ProductDocument) { if (busy) return; setBusy(item.id); try { const { restaurantId: _, ...input } = item; void _; await updateRestaurantProduct(item.id, { ...input, isAvailable: !item.isAvailable }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "تعذر تحديث توفر الأكلة."); } finally { setBusy(""); } }
  return <RestaurantShell title="إدارة الأكلات" restaurant={restaurant ?? undefined}><div className="mb-6 flex items-center justify-between gap-3"><div><p className="text-sm text-gray-500">أكلات مطعمك فقط</p><h2 className="mt-1 text-2xl font-black">قائمة الأكلات</h2></div><Link href="/restaurant-dashboard/products/add" className="flex h-11 shrink-0 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white"><Plus className="size-4" />إضافة أكلة</Link></div>{error && <AdminError message={error} onRetry={load} />}<section className="mb-5 grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-[1fr_220px_180px]"><label className="relative"><Search className="absolute top-3.5 right-3 size-4 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث باسم الأكلة" className="h-11 w-full rounded-xl border border-gray-200 pr-10 pl-3 text-sm outline-none focus:border-primary" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="التصفية حسب التصنيف" className="h-11 rounded-xl border border-gray-200 px-3 text-sm"><option value="">كل التصنيفات</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={availability} onChange={(event) => setAvailability(event.target.value)} aria-label="التصفية حسب التوفر" className="h-11 rounded-xl border border-gray-200 px-3 text-sm"><option value="">كل الحالات</option><option value="true">متوفرة</option><option value="false">غير متوفرة</option></select></section>{loading ? <AdminLoading /> : filtered.length === 0 ? <EmptyState icon={UtensilsCrossed} title="لا توجد أكلات" description={items.length ? "لا توجد نتائج مطابقة للبحث والتصفية." : "أضف أول أكلة لتظهر ضمن قائمة مطعمك."} /> : <><div className="grid gap-4 md:hidden">{filtered.map((item) => <Card key={item.id} item={item} busy={busy === item.id} onDelete={remove} onToggle={toggle} />)}</div><div className="hidden overflow-hidden rounded-3xl bg-white shadow-sm md:block"><table className="w-full text-right text-sm"><thead className="sticky top-16 bg-gray-50 text-gray-500"><tr><th className="p-4">الأكلة</th><th className="p-4">السعر</th><th className="p-4">الحالة</th><th className="p-4">مميزة</th><th className="p-4">الترتيب</th><th className="p-4">الإجراءات</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-gray-100"><td className="p-4"><Food item={item} /></td><td className="p-4 font-bold text-primary">{formatPrice(item.price)}</td><td className="p-4"><button disabled={busy === item.id} onClick={() => toggle(item)}><Availability value={item.isAvailable} /></button></td><td className="p-4">{item.isFeatured ? "نعم" : "لا"}</td><td className="p-4">{item.displayOrder}</td><td className="p-4"><Actions item={item} busy={busy === item.id} onDelete={remove} /></td></tr>)}</tbody></table></div></>}</RestaurantShell>;
}
function Food({ item }: { item: ProductDocument }) { return <div className="flex items-center gap-3"><div className="relative size-12 overflow-hidden rounded-xl bg-surface">{item.imageUrl && <Image src={item.imageUrl} alt={`صورة ${item.name}`} fill className="object-cover" sizes="48px" />}</div><span className="font-black">{item.name}</span></div>; }
function Availability({ value }: { value: boolean }) { return <span className={`rounded-full px-2 py-1 text-[11px] font-black ${value ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-500"}`}>{value ? "متوفرة" : "غير متوفرة"}</span>; }
function Actions({ item, busy, onDelete }: { item: ProductDocument; busy: boolean; onDelete: (id: string) => void }) { return <div className="flex gap-2"><Link href={`/restaurant-dashboard/products/${item.id}/edit`} aria-label={`تعديل ${item.name}`} className="grid size-9 place-items-center rounded-xl bg-gray-100"><Pencil className="size-4" /></Link><button disabled={busy} onClick={() => onDelete(item.id)} aria-label={`حذف ${item.name}`} className="grid size-9 place-items-center rounded-xl bg-red-50 text-red-600 disabled:opacity-50"><Trash2 className="size-4" /></button></div>; }
function Card({ item, busy, onDelete, onToggle }: { item: ProductDocument; busy: boolean; onDelete: (id: string) => void; onToggle: (item: ProductDocument) => void }) { return <article className="rounded-3xl bg-white p-3 shadow-sm"><Food item={item} /><div className="mt-3 flex items-center justify-between"><button disabled={busy} onClick={() => onToggle(item)}><Availability value={item.isAvailable} /></button><Actions item={item} busy={busy} onDelete={onDelete} /></div></article>; }
