import { Bike, ShoppingBag, Star, Store } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { formatArabicNumber, formatPrice } from "@/lib/format";
import type { Restaurant } from "@/types";

export function RestaurantCard({ restaurant, compact = false }: { restaurant: Restaurant; compact?: boolean }) {
  return <Link href={`/restaurants/${restaurant.id}`} className="group block overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div className={`relative overflow-hidden bg-gray-100 ${compact ? "h-32" : "h-40"}`}>{restaurant.image ? <Image src={restaurant.image} alt={`صورة ${restaurant.name}`} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width: 768px) 90vw, 340px" /> : <span className="grid h-full place-items-center text-gray-300"><Store className="size-12" /></span>}<span className={`absolute right-3 top-3 rounded-full px-3 py-1 text-[11px] font-black ${restaurant.isOpen ? "bg-emerald-500 text-white" : "bg-gray-900 text-white"}`}>{restaurant.isOpen ? "مفتوح" : "مغلق"}</span>{restaurant.rating > 0 && <span className="absolute bottom-3 left-3 flex items-center gap-1 rounded-full bg-white/95 px-2 py-1 text-xs font-black text-gray-900"><Star className="size-3.5 fill-amber-400 text-amber-400" />{formatArabicNumber(restaurant.rating)}</span>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-gray-950">{restaurant.name}</h3><p className="mt-1 line-clamp-1 text-xs text-gray-500">{restaurant.description || "مطعم محلي في بريان"}</p></div><span className="whitespace-nowrap text-xs font-bold text-primary">{formatArabicNumber(restaurant.deliveryTime || "غير محددة")}</span></div><div className="mt-4 flex flex-wrap items-center gap-3 border-t border-gray-100 pt-3 text-xs text-gray-500"><span className="flex items-center gap-1"><Bike className="size-4 text-primary" />التوصيل {formatPrice(restaurant.deliveryFee)}</span><span className="flex items-center gap-1"><ShoppingBag className="size-4 text-primary" />أقل طلب {formatPrice(restaurant.minimumOrder)}</span></div></div></Link>;
}
